### ISSUE TITLE
URWelcome Homepage - Master Task

### ISSUE THREAD

**Issue by etavenn** [saberespoder/urwelcome#1]
## Description
Limited URWelcome homepage. Responsive site. Most users on v1 and v2 will be board members, investors, contacts, friends, and family who will probably access the site mostly on desktop.

V2 requirements will be published in the next few days.

## Prioritization and Due Date
@skatkov promised 2-3 day timeline from the day requirements are submitted.  We also need to deliver SEP site in 2 weeks, and be ready to take on INE site.

## Items
Domain is -> urwelco.me
For reference, [here is the design to be edited](http://9bitinteractive.com/urwelcome/?#)
Files: [Click here for files](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXd01VckJ3Umt4U0E/view?usp=sharing)

In top-down order of placement on the page with priority level

- [x] Drop-down menu buttons
   - Remove "home". 
   - "About" takes user to ["about" section of the homepage](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXR1k5UDZqcWdnZ00/view?usp=sharing)
   - Remove "contact"

- [x] Remove "Ask your question" CTA bar. [ Replace with new CTA](https://github.com/saberespoder/urwelcome/issues/3)

- [x] [Edit value prop](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXZzR3dk1hUEZ5RHM/view?usp=sharing) to read: "URWelcome is the world’s first membership platform dedicated to connecting immigrants and their families with the information, products, and services they need to thrive in a new country. Join or support the community today"

- [x] Edit text of [second CTA "Or jump right into the discussion"](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXZnY1TEt6OUprcnM/view?usp=sharing).
    - Edit to "Visit the Spanish site!" 
    - Clicking on it opens new tab and redirects user to -> saberespoder.com

- [x] [Icons are not clickable](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXWHFtbE9zRkpRZlk/view?usp=sharing) 

- [x] Remove scary faces or do something so the display looks good on mobile and desktop. 

- [x] [Edit text associated with each "About URWelcome" icons](https://github.com/saberespoder/urwelcome/issues/2)

- [x] Remove "Jump into the convo" button and everything below it up until the "or visit our spanish..." button. In other words, [delete everything in this image.](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXM1hhUE9FTWlUZk0/view?usp=sharing) 

- [x] Edit the text of the ["or visit our spanish..." button](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXeTV6Rk9vT1FITnc/view?usp=sharing) to "Try our service in Spanish"

FOOTER ITEMS

- [x] [Make all icons and words ](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXQ2FmMEM5WVR2TUU/view?usp=sharing)in the footer not clickable.

- [x] Clicking on URWelcome takes user to the top of the page

- [x] Clicking on the SEP logo takes user to saberespoder.com

OTHER

- [x] Google Analytics

**Comment by etavenn** [comment]
oooh yeaaah, issue numbeer 1!

**Comment by etavenn** [comment]
oops, forgot to add Google Analytics. Adding it now

**Comment by FanaHOVA** [comment]
@etavenn Please provide the Google Analytics embed code :)

**Comment by FanaHOVA** [comment]
Implemented everything, just missing the CTA then we are ready to launch this. PR: https://github.com/saberespoder/urwelcome/pull/4/files

**Comment by FanaHOVA** [comment]
Missing:

- Analytics

Live at https://ur-welcome.herokuapp.com

**Comment by etavenn** [comment]
Clicking on "about" leads to about section but header bar covers "about urwelcome" text. 

![screenshot 2017-02-20 at 9 53 32 am](https://cloud.githubusercontent.com/assets/16109106/23136617/75deaeac-f752-11e6-845f-b070f1aa0ca9.png)

Header should be right above "about urwelcome" header.
![screenshot 2017-02-20 at 9 54 02 am](https://cloud.githubusercontent.com/assets/16109106/23136630/874d1cd2-f752-11e6-9d56-959d9894e0d6.png)

@FanaHOVA what about the second CTA? It's missing from the page.

**Google Analytics:**
Tracking ID: UA-92308553-1
**Tracking Code:**

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-92308553-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by FanaHOVA** [comment]
@etavenn There was no second CTA when I started working on this? Did you remove it @skatkov? 

Analytics added. 

About issue has been fixed.

**Comment by skatkov** [comment]
@FanaHOVA yeah, i've removed it. At first it seemed a bit strange to have two call for action on single page.

**Comment by etavenn** [comment]
@skatkov at first? so not anymore?

I can see how it might be strange. let's leave it out for now.

**Comment by etavenn** [comment]
@skatkov @FanaHOVA also noticed that the "about" portion is right below the CTA section whereas in the designs it is in the bottom half of the page right after the stats section. Please reverse order to how it was originally

## How it is now
![screenshot 2017-02-21 at 5 56 49 pm](https://cloud.githubusercontent.com/assets/16109106/23193706/25660a16-f85f-11e6-87cb-ce3befc1d67e.png)

## How it was in the original version.
![screenshot 2017-02-21 at 5 57 53 pm](https://cloud.githubusercontent.com/assets/16109106/23193734/495ab7fa-f85f-11e6-9a28-732f80e3248a.png)

**Comment by etavenn** [comment]
@skatkov also hold on on redirecting this page to urwelco.me. We want to get some feedback on how we can improve some of the design such as font types and colors, and element placement.

**Comment by FanaHOVA** [comment]
@etavenn Fixed. Stas had fun moving things around I guess :P

**Comment by etavenn** [comment]
@skatkov @FanaHOVA ok guys, the plan is to have urwelco.me redirect to this new homepage starting Monday morning. Here are a few last touches before we redirect it. Let me know if any of these will prevent us from going live Monday morning.

### Alignment of value prop with CTA bar
![value prop alignment](https://cloud.githubusercontent.com/assets/16109106/23293199/c01cd1f0-fa19-11e6-9924-51463967ed14.png)

### Edit the text of the value prop. 
Last sentence should be a separate line beneath the rest of the value prop.
Should read:
"The world’s first membership platform dedicated to connecting immigrants and their families with the information, products, and services they need to thrive. 
Join or support the community today!"

### Text alignment of value prop
Just going off of personal style preference and what is on the fwd.us page, I think the text should be center aligned. If you feel strongly that it should have another alignment, I trust your design eye more than mine.

### Center CTA on width of screen.  
There's more space between the end of the "join" button and the right margin vs the beginning of the "name" field box and the left margin.

### Need your feedback on these:
- Make font size of value prop text a bit bigger?  Not by much but more so it pops out more?

- Social media buttons (doesn't need to be working for Monday's release). When a user clicks on these should it allow the user to share our page on their page in the social media channel or just "like/follow"? I guess I'm talking specifically about FB right now but I think something similar applies to Twitter?

@query-string also made several recommendations which sound very solid to me. I don't know how to go about implementing them in time for Monday's release (or if it's doable) but definitely want to explore those for future iterations!

**Comment by query-string** [comment]
Will be happy to help if you need another pair of hands ;)

**Comment by FanaHOVA** [comment]
Alright, I've fixed value prop/CTA alignments. They are not 100% perfect in terms of responsiveness but you mentioned that it will mostly be desktop visits. The text is already center aligned, so not sure how to change that :)

@etavenn About sharing, there's various solutions. Find out which one you'd like to be implemented and then provide a copy for it so we can add it! For now I'm just gonna redirect the user to our social pages instead.

**Comment by etavenn** [comment]
Thanks @FanaHOVA ! I don't believe we have social media for URWelcome yet!

**Comment by etavenn** [comment]
@FanaHOVA where can I see it? Also, anything else I need to do so that it goes live on urwelco.me? I already provided @skatkov the sign-in info for the hosting site as requested. I can give those to you as well

**Comment by etavenn** [comment]
@FanaHOVA per our slack convo:

1) make the value-prop text fall within the borders of the CTA bar.
2) Length of first two lines of value prop the same. If not possible, the second line can be a bit longer
3) change "with" with "to" in the value prop

**Comment by FanaHOVA** [comment]
@etavenn Added:

<img width="1236" alt="screen shot 2017-02-27 at 12 10 16 pm" src="https://cloud.githubusercontent.com/assets/6490430/23359312/fc356052-fce5-11e6-9f81-2263e9cd298c.png">

Closing this task since v1 will go up this way, we can now have a couple days to look at it, run some ideas and then create a new list of improvements to make.
