### ISSUE TITLE
Edit text associated with each "About URWelcome" icons

### ISSUE THREAD

**Issue by etavenn** [saberespoder/urwelcome#2]
## Reqs
[This is the section.](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXSTUwU2g0bmpxTmM/view?usp=sharing) Each icon has different text associated with it.

**Icon 1 "B Certified"**
Text: "As the highest rated B corp focused on Immigrant communities in the United States, URWelcome is committed to ensuring opportunity and success for its members and their families."

**Icon 2 "US Map"**
Text: "We believe anyone should be able to live in any country and have easy access to the right information, products and services they need to build a good life. That’s why we’re using data and technology to reimagine the immigrant experience for today’s connected world. Right now we're the #1 resource for Latinos in the United States, but in the future we'll serve immigrants moving to and from countries across the globe."

**Icon 3 "Books"**
Text: "We deliver custom, data-driven recommendations and services in key categories such as Education, Healthcare, Finance, Jobs, Telecommunication, Legal, and Government Services."

**Comment by FanaHOVA** [comment]
Done
