### ISSUE TITLE
New CTA

### ISSUE THREAD

**Issue by etavenn** [saberespoder/urwelcome#3]
## Reqs
**Placement and Layout**
- Replace current CTA "ask your question" area with new CTA
- Layout should be [just like the CTA](https://drive.google.com/a/saberespoder.com/file/d/0B05Tjd1rBDKXNWU1MFk3akEwN2s/view?usp=sharing) on [fwd.us](fwd.us). Just make the font color and size match with the URwelcome site.

**FIELDS**
    - 2 fields (name, email), and "Join" button
     - Email provided should contain an "@" sign. If no "@" is provided, then user gets a flag about it and is not allowed to hit "join" until fixed.
     - Both email and name MUST be filled out to hit "enter"
     - When user clicks "enter", 
            a. email and first_name are saved in a URWelcome database.
            b. User gets a modal window with confirmation message: "Thank you! A confirmation email has been sent to you". Tech: Feel free to make the UX/UI more beautiful.

**Email**
text: "Welcome to URWelcome!"
body: "Thank you for joining! We will email you more information shortly."
Email is sent from address: [yet unknown]

**Comment by FanaHOVA** [comment]
All ready. Just need you to provide the email address when you can.

**Comment by etavenn** [comment]
@FanaHOVA will provide today. will the URW database be available in dataclips?

**Comment by FanaHOVA** [comment]
Here ya go https://dataclips.heroku.com/hwmdiddbecwyjktthnsbeoggpezm-URWelcome-Members

**Comment by etavenn** [comment]
you know what I didn't consider? If a user already exists in the database. gonna put that in for our next iteration.

**Comment by FanaHOVA** [comment]
@etavenn I was hoping that users don't have amnesia and signup for the same thing twice :) We can filter those out. I also imagine that this is just a temporary landing page.

**Comment by etavenn** [comment]
@FanaHOVA 
email -> info@urwelco.me

**Comment by FanaHOVA** [comment]
Email added. Task completed.
